name: dospace
description: Client library to interact with the DigitalOcean Spaces API. Same API as Amazon AWS S3.
version: 0.12.14
homepage: https://github.com/nbspou/dospace
author: NO-BREAK SPACE OÜ <support@no-break.space>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.5
  crypto: ^3.0.0
  http: ^0.13.0
  xml: ^5.0.2

dev_dependencies:
  test: ^1.0.0
  ini: ^2.0.1
